# Docker-compose setup used during tests
version: '3'
services:
    dask-scheduler:
        container_name: dask-scheduler
        image: daskdev/dask:dev-py3.9
        command: dask-scheduler
        environment:
            USE_MAMBA: "true"
            # TODO: remove pandas constraint once Dask images are updated
            EXTRA_CONDA_PACKAGES: "dask/label/dev::dask cloudpickle>=2.1.0 pandas>=1.5.0 scikit-learn>=1.0.0"
        ports:
            - "8786:8786"
    dask-worker:
        container_name: dask-worker
        image: daskdev/dask:dev-py3.9
        command: dask-worker dask-scheduler:8786
        environment:
            USE_MAMBA: "true"
            # TODO: remove pandas constraint once Dask images are updated
            EXTRA_CONDA_PACKAGES: "dask/label/dev::dask cloudpickle>=2.1.0 pyarrow>=6.0.1 libstdcxx-ng>=12.1.0 pandas>=1.5.0 scikit-learn>=1.0.0"
        volumes:
            - /tmp:/tmp
