version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/dask_planner"
    schedule:
      interval: "daily"
    ignore:
      # arrow and datafusion are bumped manually
      - dependency-name: "arrow"
        update-types: ["version-update:semver-major"]
      - dependency-name: "datafusion"
        update-types: ["version-update:semver-major"]
      - dependency-name: "datafusion-*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"
    ignore:
      # ignore cibw patch updates
      - dependency-name: "pypa/cibuildwheel"
        update-types: ["version-update:semver-patch"]
