version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/dask_planner"
    schedule:
      interval: "daily"
    ignore:
      # arrow and datafusion are bumped manually
      - dependency-name: "arrow"
      - dependency-name: "datafusion-*"
