python>=3.8.5
dask>=2.19.0
pandas<1.2.0 # pandas 1.2.0 introduced float NaN dtype,
             # which is currently not working with postgres,
             # so the test is failing
jpype1>=1.0.2
openjdk>=11
maven>=3.6.0
pytest>=6.0.1
pytest-cov>=2.10.1
mock>=4.0.3
sphinx>=3.2.1
tzlocal>=2.1
fastapi>=0.61.1
uvicorn>=0.11.3
pyarrow>=0.15.1
prompt_toolkit>=3.0.8
pygments>=2.7.1
dask-ml>=1.7.0
scikit-learn<0.24.0
intake>=0.6.0