name: dask-sql
channels:
- rapidsai
- rapidsai-nightly
- dask/label/dev
- conda-forge
- nvidia
- nodefaults
dependencies:
- c-compiler
- zlib
- dask>=2024.4.1
- dask-expr>=1.0.11
- fastapi>=0.92.0
- fugue>=0.7.3
- httpx>=0.24.1
- intake>=0.6.0
- jsonschema
- lightgbm
- maturin>=1.3,<1.4
- mock
- numpy>=1.22.4
- pandas>=2
- pre-commit
- prompt_toolkit>=3.0.8
- psycopg2
- pyarrow>=14.0.1
- pygments>=2.7.1
- pyhive
- pytest-cov
- pytest-rerunfailures
- pytest-xdist
- pytest
- python=3.11
- py-xgboost>=2.0.3
- scikit-learn>=1.0.0
- sphinx
- sqlalchemy
- tpot>=0.12.0
# FIXME: https://github.com/fugue-project/fugue/issues/526
- triad<0.9.2
- tzlocal>=2.1
- uvicorn>=0.14
# GPU-specific requirements
- cudatoolkit=11.8
- cudf=24.08
- cuml=24.08
- dask-cudf=24.08
- dask-cuda=24.08
- ucx-proc=*=gpu
- ucx-py=0.39
- xgboost=*=rapidsai_py*
- libxgboost=*=rapidsai_h*
