name: gpuci
channels:
  - rapidsai
  - rapidsai-nightly
  - nvidia
dependencies:
  - rust>=1.62.1
  - setuptools-rust>=1.4.1
  - cudatoolkit=11.5
  - cudf=22.08
  - cuml=22.08
  - dask-cudf=22.08
  - dask-cuda=22.08
  - numpy>=1.20.0
  - ucx-proc=*=gpu
  - ucx-py=0.27
  - xgboost=*=cuda_*
  - dask-ml>=2022.1.22
  - dask>=2022.3.0
  - fastapi>=0.69.0
  - fugue>=0.7.0
  - intake>=0.6.0
  - jsonschema
  - lightgbm
  - maturin>=0.12.8
  - mlflow
  - mock
  - nest-asyncio
  - pandas>=1.4.0
  - pre-commit
  - prompt_toolkit
  - psycopg2
  - pyarrow>=6.0.1
  - pygments
  - pyhive
  - pytest-cov
  - pytest-xdist
  - pytest
  - python=3.9
  - scikit-learn>=1.0.0
  - sphinx
  - tpot
  - tzlocal>=2.1
  - uvicorn>=0.11.3
