{% set name = "dask-sql" %}
{% set major_minor_patch = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').split('.') %}
{% set new_patch = major_minor_patch[2] | int + 1 %}
{% set version = (major_minor_patch[:2] + [new_patch]) | join('.') + environ.get('VERSION_SUFFIX', '') %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  skip: true   # [py2k]
  entry_points:
    - dask-sql-server = dask_sql.server.app:main
    - dask-sql = dask_sql.cmd:main
  string: py{{ python | replace(".", "") }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script: RUST_BACKTRACE=full {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - setuptools-rust
    - libprotobuf
  run:
    - python
    - dask >=2022.3.0
    - pandas >=1.4.0,<2.0.0
    # FIXME: handling is needed for httpx-based fastapi>=0.87.0
    - fastapi >=0.69.0,<0.87.0
    - uvicorn >=0.13.4
    - tzlocal >=2.1
    - prompt-toolkit >=3.0.8
    - pygments >=2.7.1
    - tabulate
  run_constrained:
    # FIXME: aarch64 builds require glibc>=2.32 to prevent TLS allocation error when importing;
    # is there any way we could modify the TLS model of its shared object to avoid this?
    # https://bugzilla.redhat.com/show_bug.cgi?id=1722181
    # xref: https://github.com/dask-contrib/dask-sql/issues/1169
    - __glibc >=2.32  # [aarch64]

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql-server --help
    - dask-sql --help
  requires:
    - pip

about:
  home: https://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt
