name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- adagio
- antlr4-python3-runtime<4.10  # fugue dependency; remove when we conda install fugue
- ciso8601
- dask-ml=2022.1.22
- dask=2022.3.0
- fastapi=0.61.1
- fs
- intake=0.6.0
- jpype1=1.0.2
- jsonschema
- lightgbm
- maven
- mlflow
- mock
- nest-asyncio
- openjdk=8
- pandas=1.0.2
- pip
- pre-commit
- prompt_toolkit
- psycopg2
- pyarrow=1.0.1
- pygments
- pyhive
- pytest-cov
- pytest-xdist
- pytest
- python=3.8
- qpd  # fugue dependency; remove when we conda install fugue
- scikit-learn=1.0.0
- sphinx
- tpot
- triad
- tzlocal=2.1
- uvicorn=0.11.3
- pip:
  - fugue[sql]==0.5.3
