name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- adagio
- antlr4-python3-runtime
- ciso8601
- dask-ml
- fastapi
- fs
- intake
- isort=5.7.0
- jpype1
- jsonschema
- lightgbm
- maven
- mlflow
- mock
- nest-asyncio
- openjdk=11
- pandas
- pip
- pre-commit
- prompt_toolkit
- psycopg2
- pyarrow
- pygments
- pyhive
- pytest-cov
- pytest-xdist
- pytest
- python=3.9
- scikit-learn
- sphinx
- tpot
- triad
- tzlocal
- uvicorn
- cfn-lint
- pip:
  - fugue[sql]
