name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- c-compiler
- dask>=2022.3.0
- fastapi>=0.92.0
- fugue>=0.7.3
- httpx>=0.24.1
- intake>=0.6.0
- jsonschema
- lightgbm
- maturin>=1.1,<1.2
- mlflow
- mock
- numpy>=1.21.6
- pandas>=1.4.0
- pre-commit
- prompt_toolkit>=3.0.8
- psycopg2
- pyarrow>=6.0.2
- pygments>=2.7.1
- pyhive
- pytest-cov
- pytest-rerunfailures
- pytest-xdist
- pytest
- python=3.9
- scikit-learn>=1.0.0
- sphinx
- sqlalchemy<2
- tpot>=0.12.0
- tzlocal>=2.1
- uvicorn>=0.13.4
- libprotobuf=3
- zlib
