name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- dask>=2022.3.0
- fastapi>=0.69.0
- fugue>=0.7.0
- intake>=0.6.0
- jsonschema
- lightgbm
- maturin>=0.12.8
- mlflow
- mock
- nest-asyncio
- pandas>=1.4.0
- pre-commit
- prompt_toolkit>=3.0.8
- psycopg2
- pyarrow>=6.0.1
- pygments>=2.7.1
- pyhive
- pytest-cov
- pytest-xdist
- pytest
- python=3.9
- scikit-learn>=1.0.0
- setuptools-rust>=1.4.1
- sphinx
- tpot
- tzlocal>=2.1
- uvicorn>=0.13.4
