name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- adagio>=0.2.3
- antlr4-python3-runtime>=4.9.2, <4.10.0 # Remove max pin after qpd(fugue dependency) updates their conda recipe
- black=22.3.0
- ciso8601>=2.2.0
- dask-ml>=2022.1.22
- dask>=2022.3.0
- fastapi>=0.61.1
- fs>=2.4.11
- intake>=0.6.0
- isort=5.7.0
- jsonschema>=4.4.0
- lightgbm>=3.2.1
- mlflow>=1.19.0
- mock>=4.0.3
- nest-asyncio>=1.4.3
- pandas>=1.0.0  # below 1.0, there were no nullable ext. types
- pip=20.2.4
- pre-commit>=2.11.1
- prompt_toolkit>=3.0.8
- psycopg2>=2.9.1
- pyarrow=7.0.0
- pygments>=2.7.1
- pyhive>=0.6.4
- pytest-cov>=2.10.1
- pytest-xdist
- pytest>=6.0.1
- python=3.10
- scikit-learn>=0.24.2
- sphinx>=3.2.1
- tpot>=0.11.7
- triad>=0.5.4
- tzlocal>=2.1
- uvicorn>=0.11.3
- maturin>=0.12.8
- setuptools-rust>=1.1.2
- rust>=1.59.0
- pip:
  - fugue[sql]>=0.5.3
