name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- dask-ml=2022.1.22
- dask=2022.3.0
- fastapi=0.69.0
- intake=0.6.0
- jpype1=1.0.2
- jsonschema
- lightgbm
- maven
- mlflow
- mock
- nest-asyncio
- openjdk=11
- pandas=1.1.2
- pre-commit
- prompt_toolkit
- psycopg2
- pyarrow=3.0.0
- pygments
- pyhive
- pytest-cov
- pytest-xdist
- pytest
- python=3.8
- scikit-learn=1.0.0
- sphinx
- tpot
- tzlocal=2.1
- uvicorn=0.11.3
# fugue dependencies; remove when we conda install fugue
- adagio
- antlr4-python3-runtime
- ciso8601
- fs
- fugue-sql-antlr
- pip
- qpd>0.2.7
- triad
- pip:
  - fugue[sql]==0.5.3
