name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    - name: Cache downloaded conda packages
      uses: actions/cache@v2
      with:
        path: /home/runner/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('conda.yaml') }}
    - name: Set up Python
      uses: goanpeca/setup-miniconda@v1
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install --file conda.yaml -c conda-forge
        which python
        pip install setuptools wheel twine
    - name: Build and publish
      shell: bash -l {0}
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*