name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.repository == 'dask-contrib/dask-sql'

    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-v1-jdk11-${{ hashFiles('**/pom.xml') }}
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: 3.8
          activate-environment: dask-sql
          environment-file: continuous_integration/environment-3.8-jdk11-dev.yaml
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install setuptools wheel twine
          which python
          pip list
          conda list
      - name: Build jar
        shell: bash -l {0}
        run: python setup.py java
      - name: Build and publish
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
