name: Upload Docker image

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta for main image
        id: docker_meta_main
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nbraun/dask-sql
      - name: Build and push main image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/main.dockerfile
          build-args: DOCKER_META_VERSION=${{ steps.docker_meta_main.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ steps.docker_meta_main.outputs.tags }}
          labels: ${{ steps.docker_meta_main.outputs.labels }}
          push: true

      - name: Docker meta for cloud image
        id: docker_meta_cloud
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nbraun/dask-sql-cloud
      - name: Build and push cloud image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/cloud.dockerfile
          build-args: DOCKER_META_VERSION=${{ steps.docker_meta_main.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ steps.docker_meta_cloud.outputs.tags }}
          labels: ${{ steps.docker_meta_cloud.outputs.labels }}
          push: true
