name: Build and publish nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'dask-contrib/dask-sql'

    steps:
    - uses: actions/checkout@v1
    - name: Build and publish conda package
      shell: bash -l {0}
      env:
        DASK_CONDA_TOKEN: ${{ secrets.DASK_CONDA_TOKEN }}
      run: |
        # suffix for nightly package versions
        export VERSION_SUFFIX=`date +%y%m%d`

        mamba build continuous_integration/recipe \
                    --token $DASK_CONDA_TOKEN \
                    --label dev
